tasks:
    command-0:
        command: |-
            export TZ=America/New_York
            npm run start
        dependsOn:
            - init-000
        description: init task migrated from .gitpod.yml
        name: 'Task 0: command'
        triggeredBy:
            - postDevcontainerStart
    init-000:
        command: |-
            export TZ=America/New_York
            npm install
        description: init task migrated from .gitpod.yml
        name: 'Task 0: init'
